(define (problem allOut5x5)
  (:domain allOut)
  (:objects
     row1 row2 row3 row4 row5
     col1 col2 col3 col4 col5)
  (:init
     (next-row row1 row2)          (next-column col1 col2)
     (next-row row2 row3)          (next-column col2 col3) 
     (next-row row3 row4)          (next-column col3 col4)
     (next-row row4 row5)          (next-column col4 col5) 
     
     
     (not (is-on row1 col1))         (is-leftEdge row1 col1)         (is-upEdge row1 col1)
     (not (is-on row1 col2))          (is-upEdge row1 col2)
     (not (is-on row1 col3))         (is-upEdge row1 col3)
     (not (is-on row1 col4))        (is-upEdge row1 col4)
     (not (is-on row1 col5))        (is-upEdge row1 col5)           (is-rightEdge row1 col5)
     
     (not (is-on row2 col1))         (is-leftEdge row2 col1)         
     (not (is-on row2 col2))          
     (not (is-on row2 col3))         
     (not (is-on row2 col4))
     (not (is-on row2 col5))          (is-rightEdge row2 col5)
     
     (not (is-on row3 col1))         (is-leftEdge row3 col1)         
     (not (is-on row3 col2))          
     (not (is-on row3 col3))         
     (not (is-on row3 col4))
     (not (is-on row3 col5))         (is-rightEdge row3 col5)        
     
     (not (is-on row4 col1))         (is-leftEdge row4 col1)         
     (not (is-on row4 col2))          
     (is-on row4 col3)              
     (is-on row4 col4)
     (is-on row4 col5)               (is-rightEdge row4 col5)
     
     (not (is-on row5 col1))         (is-leftEdge row5 col1)         (is-downEdge row5 col1)
     (is-on row5 col2)               (is-downEdge row5 col2)
     (not (is-on row5 col3))         (is-downEdge row5 col3)
     (is-on row5 col4)               (is-downEdge row5 col4)
     (not (is-on row5 col5))        (is-downEdge row5 col5)         (is-rightEdge row5 col5)
     
     
    )
  (:goal
   (and
     (not (is-on row1 col1))
     (not (is-on row1 col2))
     (not (is-on row1 col3))
     (not (is-on row1 col4))
     (not (is-on row1 col5))
     (not (is-on row2 col1))
     (not (is-on row2 col2))
     (not (is-on row2 col3))
     (not (is-on row2 col4))
     (not (is-on row2 col5))
     (not (is-on row3 col1))
     (not (is-on row3 col2))
     (not (is-on row3 col3))
     (not (is-on row3 col4))
     (not (is-on row3 col5))
     (not (is-on row4 col1))  
     (not (is-on row4 col2)) 
     (not (is-on row4 col3)) 
     (not (is-on row4 col4)) 
     (not (is-on row4 col5)) 
     (not (is-on row5 col1)) 
     (not (is-on row5 col2)) 
     (not (is-on row5 col3)) 
     (not (is-on row5 col4)) 
     (not (is-on row5 col5)) 
    )
    )
)